name: lt_slide_20240327
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_deck: ^0.13.0
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  auto_size_text: ^3.0.0 
  url_launcher: ^6.2.5
  custom_text: ^2.0.1
  date_time_form_field:
    git:
        url: https://github.com/Zudah228/date_time_form_field.git
        ref: 1b7db5277d39aef6d606caff11ce245abea1b342

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
